name: battery_energy_trader
channels:
  - conda-forge
dependencies:
  - python==3.9
  - pip>=24.0
  - setuptools==69.1.0
  - wheel==0.42.0
  - ipython==8.12.0
  - pandas==2.2.0
  - cvxpy==1.4.2
  - matplotlib==3.8.3
  - scikit-learn>=1.4.1
  - pytorch-lightning==2.1.3
  - statsmodels==0.14.1 
  - ipykernel==6.29.3
  - pip:
    - tensorboard==2.16.2
    - cvxpy[GLPK_MI]>=1.3.2 # [GLPK_MI,GUROBI]
    